DEFINES+=PROJECT_CONF_H=\"project-conf.h\"

all: mqtt-client mqtt-black-hole mqtt-hello-version mqtt-version-number

CONTIKI_WITH_IPV6 = 1

APPS += mqtt

CONTIKI=../..
include $(CONTIKI)/Makefile.include